import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  Armchair,
  BadgeInfo,
  Building2,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Compass,
  Copy,
  DoorClosed,
  DoorOpen,
  Download,
  Eye,
  EyeOff,
  Fence,
  FileUp,
  GitFork,
  Grid3x3,
  House,
  Import,
  Info,
  Link,
  Lock,
  LockOpen,
  LogOut,
  MapPin,
  MapPinned,
  Monitor,
  Moon,
  MousePointer2,
  MoveUpRight,
  MoveVertical,
  Navigation,
  Plus,
  Redo2,
  RefreshCw,
  Route,
  Search,
  ShieldCheck,
  ShieldPlus,
  Sparkles,
  Split,
  SquareStack,
  Store,
  Sun,
  Trash2,
  Undo2,
  UserRound,
  WavesLadder,
  Wrench,
} from "lucide-react";
import type {
  FeatureIconKey,
  NavigationEdgeIconKey,
  NavigationNodeIconKey,
  UiActionIconKey,
} from "../../lib/icons/iconRegistry";

type AppIconName = UiActionIconKey | FeatureIconKey | NavigationNodeIconKey | NavigationEdgeIconKey;

const ICONS: Record<AppIconName, LucideIcon> = {
  search: Search,
  export: Download,
  import: Import,
  add: Plus,
  delete: Trash2,
  clone: Copy,
  undo: Undo2,
  redo: Redo2,
  split: Split,
  fork: GitFork,
  select: MousePointer2,
  snap: ShieldPlus,
  grid: Grid3x3,
  compass: Compass,
  route: Route,
  clear: ShieldCheck,
  upload: FileUp,
  reset: Navigation,
  show: Eye,
  hide: EyeOff,
  lock: Lock,
  unlock: LockOpen,
  expand: ChevronRight,
  collapse: ChevronDown,
  themeDark: Moon,
  themeLight: Sun,
  directory: ClipboardList,
  entry: BadgeInfo,
  address: MapPinned,
  venue: House,
  building: Building2,
  footprint: Building2,
  level: SquareStack,
  unit: Store,
  section: SquareStack,
  geofence: Fence,
  opening: DoorOpen,
  relationship: Link,
  amenity: Sparkles,
  anchor: Anchor,
  detail: Info,
  fixture: Wrench,
  kiosk: Monitor,
  occupant: UserRound,
  entrance: DoorOpen,
  door: DoorClosed,
  stairs: WavesLadder,
  elevator: MoveVertical,
  escalator: MoveUpRight,
  revolving_door: RefreshCw,
  exit: LogOut,
  pedestrian: Route,
  wheelchair: Armchair,
  unknown: MapPin,
};

type AppIconProps = {
  name: AppIconName;
  className?: string;
  size?: number;
};

export const AppIcon = ({ name, className = "size-4", size }: AppIconProps) => {
  const Component = ICONS[name] ?? MapPin;
  return <Component className={className} {...(size ? { size } : {})} aria-hidden="true" />;
};
